# Generated by Django 4.0 on 2022-01-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_vote_current_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='current_song',
        ),
    ]
